title: Akshita Gupta # your name (or website title) here
logo: "/images/Akshita_pic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   Developer,coder,OpenCV enthusiast
  <br><br>
  Open Source Contributor, Competitive Programmer
  <br><br>
  <a href="https://www.linkedin.com/in/akshita-gupta-a4a895187">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
